# Hyperparameters - change to the parameters given in paper
MEMORY_SIZE = 1e6
MINIBATCH_SIZE = 32
EPSILON = 1
LEARNING_RATE = 1
NUM_EPISODES = 20
DECAY_RATE = 0.9 * 1e-6
MAX_EPSILON = 1.0
MIN_EPSILON = 1e-1
DISCOUNT_FACTOR = 0.99
HISTORY_LENGTH = 4
ACTION_REPEAT = 4
TARGET_NETWORK_UPDATE_FREQ = 1e5
IMG_HEIGHT = 84
IMG_WIDTH = 84
MAX_STEPS = 1e8
NOOP_MAX = 30
REPLAY_START_SIZE = 5e4